/*
 * Nurse App api documentation
 * Nurse app api with all services provided.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: marcos.echague@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package py.com.nurseapp.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PatientVitalSignDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-13T05:51:56.690-03:00")
public class PatientVitalSignDto {
  @SerializedName("codVitalSign")
  private String codVitalSign = null;

  @SerializedName("idPatient")
  private Integer idPatient = null;

  @SerializedName("valueVitalSign")
  private Integer valueVitalSign = null;

  public PatientVitalSignDto codVitalSign(String codVitalSign) {
    this.codVitalSign = codVitalSign;
    return this;
  }

   /**
   * Get codVitalSign
   * @return codVitalSign
  **/
  @ApiModelProperty(value = "")
  public String getCodVitalSign() {
    return codVitalSign;
  }

  public void setCodVitalSign(String codVitalSign) {
    this.codVitalSign = codVitalSign;
  }

  public PatientVitalSignDto idPatient(Integer idPatient) {
    this.idPatient = idPatient;
    return this;
  }

   /**
   * Get idPatient
   * @return idPatient
  **/
  @ApiModelProperty(value = "")
  public Integer getIdPatient() {
    return idPatient;
  }

  public void setIdPatient(Integer idPatient) {
    this.idPatient = idPatient;
  }

  public PatientVitalSignDto valueVitalSign(Integer valueVitalSign) {
    this.valueVitalSign = valueVitalSign;
    return this;
  }

   /**
   * Get valueVitalSign
   * @return valueVitalSign
  **/
  @ApiModelProperty(value = "")
  public Integer getValueVitalSign() {
    return valueVitalSign;
  }

  public void setValueVitalSign(Integer valueVitalSign) {
    this.valueVitalSign = valueVitalSign;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatientVitalSignDto patientVitalSignDto = (PatientVitalSignDto) o;
    return Objects.equals(this.codVitalSign, patientVitalSignDto.codVitalSign) &&
        Objects.equals(this.idPatient, patientVitalSignDto.idPatient) &&
        Objects.equals(this.valueVitalSign, patientVitalSignDto.valueVitalSign);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codVitalSign, idPatient, valueVitalSign);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatientVitalSignDto {\n");
    
    sb.append("    codVitalSign: ").append(toIndentedString(codVitalSign)).append("\n");
    sb.append("    idPatient: ").append(toIndentedString(idPatient)).append("\n");
    sb.append("    valueVitalSign: ").append(toIndentedString(valueVitalSign)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

