/*
 * Nurse App api documentation
 * Nurse app api with all services provided.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: marcos.echague@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package py.com.nurseapp.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import py.com.nurseapp.client.model.PatientVitalSignResponse;

/**
 * ResponsePatientVitalSignListDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-13T05:51:56.690-03:00")
public class ResponsePatientVitalSignListDto {
  @SerializedName("patientVitalSigns")
  private List<PatientVitalSignResponse> patientVitalSigns = null;

  public ResponsePatientVitalSignListDto patientVitalSigns(List<PatientVitalSignResponse> patientVitalSigns) {
    this.patientVitalSigns = patientVitalSigns;
    return this;
  }

  public ResponsePatientVitalSignListDto addPatientVitalSignsItem(PatientVitalSignResponse patientVitalSignsItem) {
    if (this.patientVitalSigns == null) {
      this.patientVitalSigns = new ArrayList<>();
    }
    this.patientVitalSigns.add(patientVitalSignsItem);
    return this;
  }

   /**
   * Get patientVitalSigns
   * @return patientVitalSigns
  **/
  @ApiModelProperty(value = "")
  public List<PatientVitalSignResponse> getPatientVitalSigns() {
    return patientVitalSigns;
  }

  public void setPatientVitalSigns(List<PatientVitalSignResponse> patientVitalSigns) {
    this.patientVitalSigns = patientVitalSigns;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePatientVitalSignListDto responsePatientVitalSignListDto = (ResponsePatientVitalSignListDto) o;
    return Objects.equals(this.patientVitalSigns, responsePatientVitalSignListDto.patientVitalSigns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(patientVitalSigns);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePatientVitalSignListDto {\n");
    
    sb.append("    patientVitalSigns: ").append(toIndentedString(patientVitalSigns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

